Git svn doesn't know how to follow complicated branch patterns, so I had to squash multiple commits into a single big change. I've learned, I won't do it again.
Squashed commit of the following:

commit 95d4c411d61f2e382cb029ee66527841428ff862

    Oh, duh, it's true, Java has no unsigned because Gosling found them
    too "complicated". Is it better to try and emulate them, or to give up?

    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.
    I will be able to generate Java code.

commit 578e8617e5f5c61daa9c8376ff4dc1d244d10b8f

    Added support for bytecode copy to minimize repetitions in bytecode files
    Verify the presence of bytecode functions before emitting code.

commit 377b4ebe33844d5b6f67bec32a83b065b328be57

    Add bytecode verification function.
    Add possibility to copy bytecodes to avoid repetitions in bytecode files

commit 1e10c346df8a8d166223060b307180273ea020c9

    Added support for enumeration represesentation types.
    Used it for booleans, which allows Java to pass boolean tests

commit b1c89126ad6967167367cab7630bfd4221187999

    Fixed formatting makes it easier to compare C and Java test results

commit d8d595ed614a1f7b6d4c4d0128f08b969f72f298

    Made a better loop model that allows both C and Java to generate better code.
    We now have different bytecodes depending on the type of loop.

commit a7d7bdc98aedcd5fc1ba9335a9f83b8cd79d82a6

    Make the Java tests run a little better

commit d03c3278417c8cfeb222780b8bab3d7b84151ae4

    Added info and copy bytecodes

commit fad66e1f2cbc7de36a18dddfced9e77f3e641fab

    The complex tests now look the way I wanted them.

commit d7d1d8ab85ae4588098800d72a771f19425b6a39

    Add special shortcuts with real numbers where it makes sense

commit 057e1688621e94888319f51dc007a3e2721bd2a5

    Why didn't we set the declaration machine name for built-in types?

commit cbf6011f1d40d1c67f3ba57f672580b9deb2be38

    Fixed the test for constructors so that it works fine for generic types
    This makes both the generic and non generic tests work identically

commit 27018179c07b4f510dfcb9ef72d2d1e7095eac9f

    The test for the non-generic case works.

commit 6f636a553aa22c5e3244e8f21cd755950d9b2d36

    Fix test reference

commit 2e9d8e06823d70d8d1b4170d2d69ad453054a7db

    Adventures in GIT land...

commit 60f1a238b8c0e89a1cae749d78c4bc36b7c3cb25

    Fixed last failing test on redefinition of integer, by adding a rule that
    the implicitly defined constructors and anything in a direct using scope
    is closer than anything in a named using scope like XL_BUILTINS

commit a5dfcf7d23b50445325e53955e5ec5f45c554f96

    Add the depth to the debug info in overload resolution

commit 33c6555165d052a283572c7672b5473211b55fe8

    Avoid printing out machine names in case of overloading error

commit eb68a01bc4471a9ea30390215698a54b8969b4c3

    We don't want the LLVM branch here

commit 5438452a2e5039c1664c7075fbf790db6c12a2e7

    Avoid printing out machine names in case of overloading error

commit c8b19587bf898c7c16f782fc712288d772f193f3

    This is practically the test we want

commit ca19d9e0e73a1ea9e47766be1917f996c20ff8dd

    The instantiation errors are related to different temporary numbers.

commit b4a249de1aa0b97a3d42f32fcb46dcffdb408237

    The missing destructors are expected: they are for the temporaries
    that we were creating in copy construction before.

commit 2a1ddbfe5759b2ba2fb5236f647583f0c5aec667

    Finally fixed FinalizeDeduction so that all deduction tests pass correctly.
    A few tests need revisiting, not sure if they are failures or features.

commit d5997a7889aeb2f7244c9367f17ce3d6d2fae05a

    Keep 'ctors' instrumentation, we'll probably need it in the future

commit a19b2834372be73eb5d1bf56579bfa52f2382550

    Reworked the whole finalization of generic argument so that
    return type deduction happens at the right place.
    Unfortunately, the test for generic pointers still fail, so it's not good.
    But at least, the tests for complex now deduce what I want.

commit 917819a038963f0d04335e7e5d480abffc943ef6

    No point in generating default functions for instances if the generic variant exists

commit 7380e39e178e023cc804392329470d8d03bbca1a

    Make machine names consistent

commit 8d4437c05d0580ae6820bf56e1c7191779a80559

    Beautify

commit a70be9c66d23c6512144c5c9e5fd870fed626ac0

    Added support for info

commit 6ea2727f5b7b4d850c8d98e7b18a9eb3a460401b

    Add a prefix to all traces

commit 7059ab1c72029f8db745acb0c84d6492ba6b0c34

    Make code a bit easier to trace

commit 09d1db2ded6caf4b3d4a3561738be66d3bb58a37

    Eliminated the crash scenario

commit b24150c5f507c6847d1e17eef736eb3df2c1c3bc

    Removed ddd instrumentation

commit 1202009254682a10b618c204fc1de0677ff9ab31

    Add support for reference to type constructors from within
    generic function bodies using the 'complex.value' notation.
    The positive test passes, a negative test still crashes.

commit 5ff3a55b74e07c94743385801e549c24c9cd9079

    Another typo...

commit 0a11074ddfecd4fcd330634175c9fb9dcb93dbc2

    It doesn't add value to restrict GenericIndex to function arguments

commit eab05aff79c7fd599197fa71902c4794afc7c810

    Also include @@ in the exclude pattern

commit e76109a5f8456300a4e399267ea9875bff33818a

    While testing, I noticed that IsFunction is often called with bytecodes. Created a quick path for that.

commit d2fcc9d7e6401bc0b92f0edebfd19848e4782fa6

    This is the correct test :-)

commit 7e7f36f5d23c8ee945b4bf30e268b2d147a148e1

    The tests we want to pass

commit c51eb5790db206a533f6a21dd543a6a3f14bfa20

    This version almost works. Some tests still fail hard, notably
    when generating constructors in generic types. Will need the
    code that makes complex.value(0) work before we can proceed further.

commit 76d9295a1d4232f78603626ef6c673ac6efcbe88

    Removed SplitWrite and @write, we did not seem to use them.

commit bb970f4e0f9d1d01e169f578401e59d8de99c210

    Initial LLVM entries


git-svn-id: https://xlr.svn.sourceforge.net/svnroot/xlr/trunk@396 ed21b5e9-bf16-0410-b9ea-f1dd0686f206