Bug workaround for unsatisfied symbols with recent versions of GCC
Manually add explicit template instantiations for Allocator<T>::allocator
for the symbols that happen to be missing. Hack.

/usr/bin/ld: /home/ddd/Work/xl//libxl.so: undefined reference to `XL::Allocator<XL::CompilerRewriteCalls>::allocator'
/usr/bin/ld: /home/ddd/Work/xl//libxl.so: undefined reference to `XL::Allocator<XL::Types>::allocator'
/usr/bin/ld: /home/ddd/Work/xl//libxl.so: undefined reference to `XL::Allocator<XL::CompilerRewriteCandidate>::allocator'