Imnproved fix, reverts "Remove obsolete MinGW-ism"
This reverts commit 8e640d88825d8d1175251cd417fb697f8a5df3d4 and
provides a better fix based on the existence of <sys/socket.h>

Otherwise, there is a compilation failure on Win7:

In file included from remote_module.cpp:4:0:
remote.cpp:30:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~
compilation terminated.