Attempt to reproduce LLDB bug #17941
The compiler has changed sufficiently in the past 5 years (!!!) that
the original instructions no longer apply. It might be possible to
reproduce the issue on the Tao branch, but it's unlikely.

Since the O1 compiler unit is quite obsolete and not fully repaired
yet, I tried to reproduce by adding a member that shadows a local
variable.

Results with current LLDB:

- Opt build:

frame #4: 0x00000001000f994e libxl.0.dylib`XL::CompilerUnit::Compile() [inlined] XL::CompilerUnit::Global(this=<unavailable>, tree=<unavailable>, value=<unavailable>) at compiler-unit.cpp:217 [opt]
   214 	//    Record the global value associated to a tree
   215 	// ----------------------------------------------------------------------------
   216 	{
-> 217 	    globals[tree] = value;
   218 	}
   219 	
   220 	
(lldb) p value
error: Couldn't materialize: couldn't get the value of variable value: variable not available
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression

(This is probably the original case where the local variable had been
eliminated from debug records, and the member was shown instead)


- Debug build: seems to work

There is a running process, kill it and restart?: [Y/n] y
Process 47165 exited with status = 9 (0x00000009) 
Process 47187 launched: '/Users/ddd/Work/Xcode/xl/xl/xl' (x86_64)
Process 47187 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
    frame #0: 0x0000000100129eb8 libxl.0.dylib`XL::CompilerUnit::Global(this=0x00007ffeefbfeb88, tree=0x000000010354ec58, value=0x0000000103027708) at compiler-unit.cpp:217:21
   214 	//    Record the global value associated to a tree
   215 	// ----------------------------------------------------------------------------
   216 	{
-> 217 	    globals[tree] = value;
   218 	}
   219 	
   220 	
Target 0: (xl) stopped.
(lldb) p value
(XL::Value_p) $0 = 0x0000000103027708